### PR TITLE
Add due date to possible variables

### PR DESCRIPTION
**Pull request by MaciekBaron**
This change adds a due date field

### CODE REVIEW

**Comment by MaciekBaron** [comment]
Hi @urossmolnik I was wondering if you'd have time to have a look at this small PR? Being able to set a due date would be really helpful. Thank you!

**Review by urossmolnik — APPROVED** [review]

**Comment by urossmolnik** [comment]
Hi @MaciekBaron, thanks for this. One small change request to better describe due date format. 
ISO 8601 format will work too, but we automatically strip time part from due dates.

**Comment by MaciekBaron** [comment]
Thanks! I committed that suggestion now.

**Comment by urossmolnik** [comment]
@MaciekBaron Zapier app is published. It should now be possible to set `dueDate`.

**Pull request merged**
